Add Fanvil X[3-6]U & X210
wazo-platform/wazo-provd-plugins pull request #140
Opened 2022-06-04 13:37 UTC by slemoal-oci

Ajout des modèles fanvil
X3U, X4U, X5U, X6U, X210

2022-06-07 20:21 UTC, bloom1 requested changes
Hello @slemoal-oci!

Thank you for the PR :smile:

Two points:
- There are multiple `*.bak` files in the diff. Please make sure to remove these!
- If you want the plugin to be built by our system and upgraded by everyone, you must increment the plugin version number in the `plugin-info` file. 

Thank you!

2022-06-09 19:33 UTC, bloom1 requested changes

2022-06-09 19:33 UTC, bloom1 commented on plugins/wazo-fanvil/serie-x/pkgs/pkgs.db
> +sha1sum: d18508f3c83d625e4e192dc08bd0d023
The `sha1sum` are not valid for all the new firmwares
It is not the same as an `md5`

2022-08-17 18:42 UTC, sopelj commented
recheck

2022-11-11 12:30 UTC, fblackburn1 commented
@bloom1 any blockers on this PR?

2022-11-11 13:36 UTC, sopelj commented
> @bloom1 any blockers on this PR?

Most of these phones (all but the X3U, are now supported in master) were added in another PR (#157) at the same time as the pros (PR #156). Because the way the config files were loaded needed to be changed in order to support firmware upgrades on both the "pro" and "non pro" models, since they use the same config names, but require different firmware.
 
The newer x-series phones should now extend `new-base.tpl`. This PR could possible be updated to just add the X3U phone.

2023-04-07 13:29 UTC, bloom1 commented
No reply from PR author, closing it.

2023-04-07 13:29 UTC, closed without merging