fix : Add new MAC Prefix 70:1f:53 (SPA8000)
wazo-platform/wazo-provd-plugins pull request #183
Opened 2023-02-10 16:08 UTC by PJODSTNY

New Cisco SPA8000 can come with MAC address prefix 70:1f:53

Consider adding this block inside linksys.conf dhcp_update file

subclass "voip-mac-address-prefix" 70:1f:53:a0 {
    if not exists vendor-class-identifier {
        option tftp-server-name = config-option VOIP.tftp-server-name;
        log(concat("[", binary-to-ascii(16, 8, ":", hardware), "] ", "BOOT Linksys PREFIX 70:1f:53:a0"));
    }
}

2023-02-13 15:37 UTC, bloom1 requested changes

2023-02-13 15:37 UTC, bloom1 commented on dhcp/dhcp/dhcpd_update/linksys.conf
> +subclass "voip-mac-address-prefix" 70:1f:53:a0 {
Thank you for the contribution!
However, the MAC prefix should be written like the others. The first byte is always 1.
So it should be `1:70:1f:53`

Thanks :smile:

2023-02-28 09:38 UTC, PJODSTNY commented
Hello, Correct mac syntax have been made on the file :)

2023-03-01 16:09 UTC, bloom1 approved these changes

2023-03-01 16:12 UTC, merged