WAZO-2259: update plugins metadata
wazo-platform/wazo-provd-plugins pull request #80
Opened 2021-02-19 12:09 UTC by bloom1

ALL plugins will need to be rebuilt & repushed on stable after this.

2021-02-19 12:20 UTC, bloom1 commented
recheck

2021-02-19 12:24 UTC, sboily requested changes

2021-02-19 12:24 UTC, sboily commented on plugins/xivo-aastra/3.3.1-SP4/plugin-info
> +            "type": "deskphone",,
Double comma

2021-02-19 12:24 UTC, sboily commented on plugins/wazo-snom/8.7.5.35/plugin-info
> +            "type": "bridge",
What is bridge? It's a pager.

2021-02-19 12:24 UTC, sboily commented on plugins/xivo-aastra/3.3.1-SP4/plugin-info
> +            "type": "deskphone",,
Double comma

2021-02-23 20:22 UTC, fblackburn1 requested changes
I'm not sure what to review, according the ticket all plugin should implement keys defined in the readme

The funny command to find them:
```shell
find -name plugin-info -exec jq --arg filename {} '.capabilities[] | select( has("type") == false ) | $filename' {} \;
```

high_availability is missing:
* xivo-cisco-sccp/wireless-1.4.5/plugin-info
* xivo-cisco-sccp/9.4/plugin-info
* xivo-cisco-sccp/cipc-2.1.2/plugin-info
* xivo-cisco-sccp/8.5.2/plugin-info
* xivo-cisco-sccp/legacy/plugin-info

expansion_modules is missing:
* wazo-fanvil/serie-x/plugin-info

switchboard is missing:
* ./xivo-zenitel/01.11.3.2/plugin-info
* xivo-grandstream/1.0.8.6/plugin-info
* ./wazo-fanvil/serie-x/plugin-info
* ./wazo-fanvil/2.3/plugin-info
* ./wazo-htek/2.0.4.4.58/plugin-info
* ./wazo-htek/2.0.4.6.41/plugin-info
* ./xivo-cisco-sccp/wireless-1.4.5/plugin-info
* ./xivo-cisco-sccp/9.4/plugin-info
* ./xivo-cisco-sccp/cipc-2.1.2/plugin-info
* ./xivo-cisco-sccp/8.5.2/plugin-info
* ./xivo-cisco-sccp/legacy/plugin-info
* ./xivo-technicolor/TB30-1.74.0/plugin-info
* ./xivo-technicolor/ST2022-4.78.1/plugin-info
* ./xivo-technicolor/ST2030-2.74/plugin-info
* ./xivo-yealink/v73/plugin-info
* xivo-yealink/v85/plugin-info
* ./xivo-yealink/v80/plugin-info
* ./xivo-yealink/v83/plugin-info
* ./xivo-yealink/v82/plugin-info
* ./xivo-yealink/v84/plugin-info
* ./xivo-yealink/v81/plugin-info

type is misisng:
* "./xivo-grandstream/1.0.8.6/plugin-info"
* "./wazo-snom/8.7.5.35/plugin-info"
* "./wazo-snom/8.9.3.80/plugin-info"
* "./core/zero/plugin-info"
* "./core/null/plugin-info"

2021-02-23 20:22 UTC, fblackburn1 commented on plugins/xivo-yealink/v73/plugin-info
> +            "type": "deskphone",
duplicate

2021-02-25 17:59 UTC, fblackburn1 approved these changes

2021-02-25 18:05 UTC, merged